### ISSUE TITLE
模型训练中断

### ISSUE THREAD

**Issue by 4465** [zjunlp/OpenUE#10]

**Comment by 4465** [comment]
>  sh predict.sh ske

![image](https://user-images.githubusercontent.com/30649756/110563837-da1f0980-8186-11eb-8ded-96309bed73d1.png)
请问这个怎么解决

**Comment by OliviaLee1997** [comment]
> > sh predict.sh ske
> 
> ![image](https://user-images.githubusercontent.com/30649756/110563837-da1f0980-8186-11eb-8ded-96309bed73d1.png)
> 请问这个怎么解决

predict.sh 中一共三个python程序。
【1】第一个python程序运行完后会在\output\predicate_infer_out\wwm\epoch6路径下生成txt文件。
【2】第二个python程序
`python openue/classification/prepare_data_for_labeling_infer.py raw_data/ske`
会读取第一个python代码生成的txt文件，在openue\sequence_labeling\sequence_labeling_data\raw_data\ske\test路径下生成**token_in_and_one_predicate.txt**文件。

我这边测试运行是没有问题的。

所以可能情况有：
【1】你是不是第一个python程序没有运行完呢？
【2】我这边数据事实上是raw_data/ske路径下存储的，因此是python xxxx.py raw_data/ske。建议看下是否是**参数**写错了。

**Comment by zxlzr** [comment]
您好，我们已经发布了基于pytorch的新版openue并提供了更加详细的文档，请您移步pytorch版本 https://github.com/zjunlp/OpenUE
