### ISSUE TITLE
按照ske.ipynb的流程测试，但是F1值为0，ner和seq的指标值也很低，这个是什么原因

### ISSUE THREAD

**Issue by LB0828** [zjunlp/OpenUE#13]
您好，我按照ske.ipynb的流程测试，但是结果很不理想，是超参设置的问题吗，按照默认config设置超参，无论是哪个任务F1值都很低
![image](https://user-images.githubusercontent.com/38499461/140676442-27186074-e757-4f13-badb-e434bf141020.png)

**Comment by CheaSim** [comment]
你好，应该是config超参设置的问题，我为了演示方便设置过以下参数 `max_steps` `limit_train_batches` `max_epochs`，请确保这三个参数分别为 0,0(也就是不限制)，和5. 你可以考虑单独运行bash脚本，bash脚本的超参数都是正常运行的超参。 

此外，能否看一下训练的步数？ 一般如果步数很低 比如32,1000之内的都应该是config设置存在一些问题，没有跑完整个数据集。

**Comment by PeirongLiL** [comment]
作者你好，config在哪里设置啊，然后训练的epoch设置多少比较合适呢，我有与题主一样的问题
