### ISSUE TITLE
一些运行在Google Colab的问题

### ISSUE THREAD

**Issue by pxlsdz** [zjunlp/OpenUE#14]
您好，最后的模型保存在哪里？我是用Google Colab训练的。
而且我发现Google Colab是否没有写完，我参照ske.ipynb编写实体识别模块，但是出现了如下错误：
![image](https://user-images.githubusercontent.com/43774986/142208168-85f2b152-94c5-406f-a701-26734e43ea66.png)
您能否提供更完整的版本？

**Comment by CheaSim** [comment]
你好，这个问题应该是pytorch_lightning版本问题，请确保pytorch_lightning版本 >1.3.1。

如果使用colab进行训练，可以参考README中colab版本的https://colab.research.google.com/drive/1VNhFYcqDbXl1b3HzU8sc-NgbhV2ZyYzW?usp=sharing。 可以在args中设置合理的超参进行训练。

**Comment by pxlsdz** [comment]
感谢您的及时回复，我想问一下在Google colab运行的时候，需要考虑修改config文件下的这两个参数吗？
![image](https://user-images.githubusercontent.com/43774986/142216281-529e0074-c7a3-4ebb-8d69-04482a2c99cf.png)
或者你可以告诉我她的意思吗？因为我运行完之后没有看到保存的模型

**Comment by pxlsdz** [comment]
我的pytorch_lightning版本是1.5.1，但依旧会出现问题
![image](https://user-images.githubusercontent.com/43774986/142397017-65f8b388-5380-4227-be9c-399c821f9834.png)
![image](https://user-images.githubusercontent.com/43774986/142397114-f9b0d190-3c32-46c6-aa87-f952b323bd8e.png)

**Comment by CheaSim** [comment]
不好意思，pytorch_lightning 1.5.1 好像有优化器设置不兼容的问题，最好使用pytorch_lightning==1.3.1.

**Comment by CheaSim** [comment]
> 感谢您的及时回复，我想问一下在Google colab运行的时候，需要考虑修改config文件下的这两个参数吗？ ![image](https://user-images.githubusercontent.com/43774986/142216281-529e0074-c7a3-4ebb-8d69-04482a2c99cf.png) 或者你可以告诉我她的意思吗？因为我运行完之后没有看到保存的模型

https://colab.research.google.com/drive/1VNhFYcqDbXl1b3HzU8sc-NgbhV2ZyYzW?usp=sharing 推荐你使用这个colab代码的复制，我运行是没有问题的。
