### ISSUE TITLE
colab模型路径保存问题

### ISSUE THREAD

**Issue by pxlsdz** [zjunlp/OpenUE#15]
![image](https://user-images.githubusercontent.com/43774986/142378858-5b7a02f7-f6c3-49a6-b835-3b1d5a7345e5.png)
cloab 运行显示保存模型路径为None，请问我应该在哪里设置？

**Comment by CheaSim** [comment]
模型保存路径是根据`ModelCheckpoint`这个回调类来定义的， 
```python
model_checkpoint = pl.callbacks.ModelCheckpoint(monitor="Eval/f1", mode="max",
    filename='{epoch}-{Eval/f1:.2f}',
    dirpath="output",
    save_weights_only=True
)
```
请确保你定义了正确的保存指标，比如`Eval/f1`，之后设置了`dirpath`和`filename`。
如果你想使用transformers的模型保存函数`save_pretrained`，可以在最后加上
```python
litmodel.model.save_pretrained(path)
tokenizer.save_pretrained(path)
```
