### ISSUE TITLE
请问ske.ipynb中的数据集../dataset/ske/train.json可以提供吗？原始下载路径http://lic2019.ccf.org.cn/kg似乎失效

### ISSUE THREAD

**Issue by PolarisRisingWar** [zjunlp/OpenUE#17]
您好！我想尝试运行OpenUE的ske.ipynb代码，我在网上查询SKE数据集的下载源为http://lic2019.ccf.org.cn/kg ，但是我无法打开这个网址（2021.12.8 20:07），可能是因为原网址失效了。
所以想请问您这边可以直接提供原数据吗？或者有其他下载路径也可以？
非常感谢！

**Comment by CheaSim** [comment]
Hello, you can download the dataset via this link. http://47.92.96.190/dataset/ske.tar.gz
