### ISSUE TITLE
源代码能做事件抽取吗

### ISSUE THREAD

**Issue by wn1652400018** [zjunlp/OpenUE#19]
源代码能做事件抽取吗

**Comment by zxlzr** [comment]
您好，源代码是可以做无触发词的事件抽取的，把事件识别当做分类任务，论元检测当做序列标注任务，使用一样的框架就可以了，数据集可以参考https://aistudio.baidu.com/aistudio/projectdetail/2147327?channelType=0&channel=0

**Comment by wn1652400018** [comment]
感谢感谢！
