### ISSUE TITLE
colab无法做验证模型

### ISSUE THREAD

**Issue by pxlsdz** [zjunlp/OpenUE#20]
![image](https://user-images.githubusercontent.com/43774986/146951732-a9abf4be-15d6-4df5-9ef6-c9c0dfc53ed3.png)
您好，问一下 ske.ipynb 的验证模块在colab怎么不行？出现上述错误。

**Comment by CheaSim** [comment]
验证模块需要在infer.yaml配置文件中设置`ner_model`和`seq_model`，分别对应训练好的命名实体识别模块保存路径和关系分类识别模块。
```yaml
ner_model_name_or_path: ner_model # path 
seq_model_name_or_path: seq_model # path
```
