### ISSUE TITLE
loss不变

### ISSUE THREAD

**Issue by zhaogangthu** [zjunlp/OpenUE#21]
作者你好，我跑了pytorch版本两个脚本run_ner.sh，run_seq.sh，发现loss都没有变化，训练到最后评价指标也都是接近于0，请问是哪里设置不对吗？

**Comment by CheaSim** [comment]
这部分可能是pytorch_lightning 版本问题， 请确保 `pytorch_lightning <= 1.3.1`

**Comment by zhaogangthu** [comment]
确实是版本的问题，没想到高版本不兼容低版本
