### ISSUE TITLE
怎么用这个将已经训练好的模型进行知识抽取呢

### ISSUE THREAD

**Issue by PeirongLiL** [zjunlp/OpenUE#22]
这个代码是否包含将数据知识抽取的代码啊，我只找到了训练的

**Comment by CheaSim** [comment]
`https://github.com/zjunlp/OpenUE/blob/main/scripts/interactive.sh` 这个脚本是使用已经训练好的`ner_model`和`seq_model`进行知识抽取。
如果想对无标注的纯文本进行抽取，可以在初始化模型`Inference`之后使用以下代码进行抽取。
```python
inputs = data.tokenizer("姚明出生在中国。", return_tensors='pt')
print(lit_model.inference(inputs))
```

**Comment by PeirongLiL** [comment]
学长我刚刚把interactive.sh跑了一边，最后的结果是会保存在./dataset/ske/cached_train_BertTokenizerFast_interactive中吗?如果是的话能否请教下如何打开这个CACHED文件0.0

**Comment by PeirongLiL** [comment]
就是知识抽取出来的结果。。。

**Comment by CheaSim** [comment]
`./dataset/ske/cached_train_BertTokenizerFast_interactive`是缓存训练样本用的，不会保存得到的三元组。
`interactive.sh`脚本是用来合并`ner_model`和`seq_model`并得到具体的比如`F1`的指标并不会保存抽取的三元组(计算F1后就扔了）。
如果想得到单一句子中抽取出来的三元组，可以使用`lit_model.inference(inputs)`单独使用模型去抽取句子的实体或者你可以在`lit_model.test_step`和`lit_model.test_epoch_end`中修改代码来保存得到的三元组。

**Comment by PeirongLiL** [comment]
谢谢学长

**Comment by jjjjjjjjj58** [comment]
学长我现在在尝试把数据集换掉，因为我的数据集是没有rel2id.josn文件的。请问如果predicate里有重复的话，比原来的少几个就要用几个EMPTY来代替，还是多个共用一个empty代替。举个例子比如我有53种predicate，但是只有49个不重复的，那么我要一个empty还是4个empty呢

**Comment by PeirongLiL** [comment]
作者你好，config在哪里设置啊，然后训练的epoch设置多少比较合适呢

**Comment by CheaSim** [comment]
`config` 是根据`yaml`文件设置的。 如果是使用脚本运行，那么直接在运行的脚本中加入命令 `--key value`即可。

**Comment by jjjjjjjjj58** [comment]
![图片](https://user-images.githubusercontent.com/75237078/148688663-ab7bcc98-8cf2-43c4-aee3-7382ecb868a7.png)
是三个脚本都设置成0，0，5嘛，还是仅仅设置interative的呢

**Comment by PeirongLiL** [comment]
请问是否所有的脚本都需 max_steps limit_train_batches max_epochs，改为 0,0(也就是不限制)，和5呢，我ner.sh与seq.sh更改后都出现了的BUG，很奇怪。。。（更改前没有问题）
![图片](https://user-images.githubusercontent.com/75237078/148689185-ca427f11-aa7d-4364-a483-9b7c681b154d.png)

**Comment by PeirongLiL** [comment]
![图片](https://user-images.githubusercontent.com/75237078/148691253-b45ffebb-08e6-4462-8766-c74d86e103c5.png)
这是SEQ.SH的结果

**Comment by CheaSim** [comment]
针对不同的数据集需要不同的超参，有的时候需要更多的`epochs`，出现的那个bug检查一下`test_only`是否启用的，那个是用来推理的。
