### ISSUE TITLE
数据集格式问题

### ISSUE THREAD

**Issue by qinglongheu** [zjunlp/OpenUE#27]
英文数据集的格式和中文数据集一样吗？能否提供一下英文数据集

**Comment by zxlzr** [comment]
您好，英文数据集格式和中文数据集一样的，英文的ace数据集受到版权问题不公开的 您可以从https://catalog.ldc.upenn.edu/LDC2006T06 下载从https://github.com/nlpcl-lab/ace2005-preprocessing 做预处理，atis等数据集您可以从这里下载https://github.com/yuanxiaosc/BERT-for-Sequence-Labeling-and-Text-Classification/tree/master/data/atis_Intent_Detection_and_Slot_Filling/train
