### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

### ISSUE THREAD

**Issue by shnyyds** [zjunlp/OpenUE#29]
运行./scripts/run_ner.sh
报错：
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main()
  File "main.py", line 73, in main
    parser = _setup_parser()
  File "main.py", line 33, in _setup_parser
    trainer_parser = pl.Trainer.add_argparse_args(parser)
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

**Comment by shnyyds** [comment]
running install
/home/shn/anaconda3/envs/openue/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/shn/anaconda3/envs/openue/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing src/openue.egg-info/PKG-INFO
writing dependency_links to src/openue.egg-info/dependency_links.txt
writing requirements to src/openue.egg-info/requires.txt
writing top-level names to src/openue.egg-info/top_level.txt
reading manifest file 'src/openue.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/openue.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/openue
creating build/bdist.linux-x86_64/egg/openue/models
copying build/lib/openue/models/__init__.py -> build/bdist.linux-x86_64/egg/openue/models
copying build/lib/openue/models/model.py -> build/bdist.linux-x86_64/egg/openue/models
creating build/bdist.linux-x86_64/egg/openue/lit_models
copying build/lib/openue/lit_models/base.py -> build/bdist.linux-x86_64/egg/openue/lit_models
copying build/lib/openue/lit_models/__init__.py -> build/bdist.linux-x86_64/egg/openue/lit_models
copying build/lib/openue/lit_models/transformer.py -> build/bdist.linux-x86_64/egg/openue/lit_models
copying build/lib/openue/lit_models/metric.py -> build/bdist.linux-x86_64/egg/openue/lit_models
creating build/bdist.linux-x86_64/egg/openue/data
copying build/lib/openue/data/utils.py -> build/bdist.linux-x86_64/egg/openue/data
copying build/lib/openue/data/data_module.py -> build/bdist.linux-x86_64/egg/openue/data
copying build/lib/openue/data/base_data_module.py -> build/bdist.linux-x86_64/egg/openue/data
copying build/lib/openue/data/processor.py -> build/bdist.linux-x86_64/egg/openue/data
copying build/lib/openue/data/__init__.py -> build/bdist.linux-x86_64/egg/openue/data
copying build/lib/openue/__init__.py -> build/bdist.linux-x86_64/egg/openue
byte-compiling build/bdist.linux-x86_64/egg/openue/models/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/models/model.py to model.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/lit_models/base.py to base.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/lit_models/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/lit_models/transformer.py to transformer.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/lit_models/metric.py to metric.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/data/utils.py to utils.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/data/data_module.py to data_module.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/data/base_data_module.py to base_data_module.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/data/processor.py to processor.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/data/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/openue/__init__.py to __init__.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openue.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openue.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openue.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openue.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openue.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/openue-0.2.5-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing openue-0.2.5-py3.8.egg
Removing /home/shn/anaconda3/envs/openue/lib/python3.8/site-packages/openue-0.2.5-py3.8.egg
Copying openue-0.2.5-py3.8.egg to /home/shn/anaconda3/envs/openue/lib/python3.8/site-packages
Adding openue 0.2.5 to easy-install.pth file

Installed /home/shn/anaconda3/envs/openue/lib/python3.8/site-packages/openue-0.2.5-py3.8.egg
Processing dependencies for openue==0.2.5
Searching for pytorch_lightning==2.0.1
Reading https://pypi.org/simple/pytorch_lightning/
Downloading https://files.pythonhosted.org/packages/ae/35/54b5ed7577816d7c1362c1102459c40b83986c21a60c526be68477fc8312/pytorch_lightning-2.0.1-py3-none-any.whl#sha256=842aee8bd4b79b7fbb6d5709c10f3c239e7c75284f6b0e775d0047e1dba0c519
error: The read operation timed out
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main()
  File "main.py", line 73, in main
    parser = _setup_parser()
  File "main.py", line 33, in _setup_parser
    trainer_parser = pl.Trainer.add_argparse_args(parser)
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'
完整报错

**Comment by zxlzr** [comment]
您好，从报错情况看应该是python的包版本问题，建议您使用低版本的包重试一下。另外openue已停止维护，建议您移步https://github.com/zjunlp/DeepKE
