### ISSUE TITLE
关于训练语料

### ISSUE THREAD

**Issue by jimmy-walker** [zjunlp/OpenUE#3]
感谢你的工作。请问训练语料有哪些呢？是基于开源的语料训练的吗

**Comment by jimmy-walker** [comment]
已经看到您关于Entity and Realation Extraction的语料来源于ske。
请问这两部分的功能的语料是从哪来的呢？
Intent and Slot Filling
Opinion and Apspect Extraction

**Comment by zxlzr** [comment]
您好，目前版本还在开发中，未正式release，Intent and Slot Filling
Opinion and Apspect Extraction 均使用学术数据集谢谢。

**Comment by jimmy-walker** [comment]
> 您好，目前版本还在开发中，未正式release，Intent and Slot Filling
> Opinion and Apspect Extraction 均使用学术数据集谢谢。

@zxlzr 请问能告知下相关的学术数据集是哪些吗？
