### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by ChloeJKim** [zjunlp/OpenUE#4]
Hi

Great work! I want to try out the model and while running the first step: 
1. Data Preprocessing. Put the pretrained language model (e.g., BERT) in the pretrained_model folder and put all raw data (run script download_ske.sh in the benchmark folder) in the raw_data folder.

I couldn't find the benchmark folder and the script 'download_ske.sh' 
![image](https://user-images.githubusercontent.com/52466133/93040893-eecb7c00-f5ff-11ea-8f8b-53171cc8c108.png)

I also could not find these scripts in any folders for step 4
sh export_seq.sh ske
sh serving_cls.sh ske

can you help me?

**Comment by zxlzr** [comment]
Sorry for the missing files.

Those files are available now. 
https://github.com/zjunlp/openue/blob/master/pretrained_model/download_bert_cn.sh
https://github.com/zjunlp/openue/blob/master/raw_data/download_ske_dataset.sh
https://github.com/zjunlp/openue/blob/master/export_seq.sh
https://github.com/zjunlp/openue/blob/master/serving.sh

We are also developing a Pytorch version and will be released soon. Feel free to try it.

**Comment by ChloeJKim** [comment]
thank you for the quick reply. I was wondering if the model only available for Chinese?

I tried running **sh preprocess.sh ske** but it seemed that this was looking for chinese bert
![image](https://user-images.githubusercontent.com/52466133/93165984-52be7500-f6d2-11ea-8a25-d414ec0b2921.png)

Is there a way to run this on English version? (I also downloaded english bert) 

Thank you!

**Comment by zxlzr** [comment]
You can change the line 9 and line 10 with the English bert in the file config.py.  
![image](https://user-images.githubusercontent.com/1264492/93168859-6f9c8c00-f756-11ea-9204-06e463fade23.png)

**Comment by ChloeJKim** [comment]
do you by any chance have a sample of prediction for English version?

**Comment by zxlzr** [comment]
just use the same input format like:  oneline with  {"text":"Obama was born in Honolulu", "spo_list":["predicate":"borin_in","subject":"Obama","object":"Honolulu"]}

**Comment by ChloeJKim** [comment]
sorry for a lot of questions, what dataset was the model trained on? 
can I train with a new dataset? & and if you can provide methods? it would be great :) 
Thank you

**Comment by zxlzr** [comment]
we train the model with NYT, WebNLG, and Wikidata which can be obtained from  https://github.com/zjunlp/IEDatasetZoo. 
Feel free to train a new dataset, but the hyperparameter optimization is boring.

**Comment by ChloeJKim** [comment]
when I use **download_ske_dataset.sh** I get chinese raw_data. 
Can you provide a link that provides english raw data?

**Comment by zxlzr** [comment]
You can obtain nyt and webnlg from https://github.com/weizhepei/CasRel/tree/master/data  and   wikidata from https://public.ukp.informatik.tu-darmstadt.de/UKP_Webpage/DATA/WikipediaWikidataDistantSupervisionAnnotations.v1.0.zip
