### ISSUE TITLE
More Documentation in English

### ISSUE THREAD

**Issue by tanmayag78** [zjunlp/OpenUE#7]
Hey, first of all, great work. Loved your work in this field. 
I think Event Extraction is not working properly on the demo page(http://openue.top/index.html). Can you have a look at it?
Another request is to prepare the documentation in English. A lot of people will be having many questions about the dataset used, entities on which model is trained, pretrained model f scores, and so on.

Whenever I hover over the Knowledge graph in demo page, it shows something in Chinese which I am not able to understand. Can you have a look at it? Secondly how about showing the predicate instead of the predicate code.

**Comment by zxlzr** [comment]
We will release more detailed English documents soon.
