### ISSUE TITLE
您好，demo没跑起来，遇到了几个问题，麻烦确认下

### ISSUE THREAD

**Issue by gongtu** [zjunlp/OpenUE#9]
1、README_CN.md文件中，python predict.sh ske 应该改为sh predict.sh ske；
2、openue/__init__.py中，所有"/home/ningyu.zny/work/OpenUE/pretrained_model/chinese_wwm_ext_L-12_H-768_A-12/bert_config.json"全路径应该改为相对路径；

能否发一份跑好的模型”ske_bert_entity_relation“到我邮箱？ 1766060046@qq.com 
感谢🙏

**Comment by zxlzr** [comment]
您好，我们已经发布了基于pytorch的新版openue并提供了更加详细的文档，请您移步pytorch版本 https://github.com/zjunlp/OpenUE
